### ISSUE TITLE
"Your connection is not secure" on https

### ISSUE THREAD

**Issue by peteruithoven** [micahilbery/micahilbery.github.io#5]
I'm getting a big "Your connection is not secure" error when visiting your site over https. Thought you should know. 
![screenshot from 2018-02-09 20 55 33](https://user-images.githubusercontent.com/523210/36047179-9b902d92-0ddb-11e8-9de6-ebc66b9885f2.png)

**Comment by TraumaD** [comment]
Yeah, this is because GitHub doesn't support Https with custom domain names AFAIK. I have thought about getting around this using cloudflare or something but haven't had the time to research it properly. I plan to address this somehow with the rewrite.

**Comment by micahilbery** [comment]
I believe I have fixed this with my new domain and a cloudflare setup. It might take a little while for it all to push through though.

**Comment by micahilbery** [comment]
I'm pretty sure it's fixed now 👍

**Comment by peteruithoven** [comment]
Yes :)

**Comment by micahilbery** [comment]
Now I'm trying to use githubs built in https support and nothing works now :man_shrugging: I'll hopefully figure it out soon.

**Comment by micahilbery** [comment]
YAY! 🎉 It works again! I did the equivalent of turning it off and on again so 🤷‍♂️ but who cares it works.
